### ISSUE TITLE
I need a plugin, can you help?

### ISSUE THREAD

**Issue by XxBonf1r3xX** [Bluscream/BetterDiscord-Plugins-and-Themes#18]
I would love to get a plugin which would remove users avatars from the right hand side panel and only show usernames.

**Comment by holly-hacker** [comment]
Just use this custom CSS

```css
.channel-members-wrap .member .avatar-small {
    display: none;
}
```
